resourceRules:
  cpu:
    containerQuery: |
      sum by (<<.GroupBy>>) (
        rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>,container!=""}[1m])
      )
    nodeQuery: |
      sum by (<<.GroupBy>>) (
        label_join((kube_pod_info{pod=~"node-exporter-.*",<<.LabelMatchers>>}), "kubernetes_pod_name", "", "pod") * on(kubernetes_pod_name) group_right(node)
        (sum by(kubernetes_pod_name) (1 - rate(node_cpu_seconds_total{mode="idle",kubernetes_pod_name=~"node-exporter-.*"}[1m])))
      )
    resources:
      overrides:
        node:
          resource: node
        namespace:
          resource: namespace
        pod:
          resource: pod
    containerLabel: container
  memory:
    containerQuery: |
      sum by (<<.GroupBy>>) (
        container_memory_usage_bytes{<<.LabelMatchers>>,container!=""}
      )
    nodeQuery: |
      sum by (<<.GroupBy>>) (
        label_join((kube_pod_info{pod=~"node-exporter-.*",<<.LabelMatchers>>}), "kubernetes_pod_name", "", "pod") * on(kubernetes_pod_name) group_right(node)
        (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)
      )
    resources:
      overrides:
        node:
          resource: node
        namespace:
          resource: namespace
        pod:
          resource: pod
    containerLabel: container
  window: 5m
