apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: front-proxy-client:system:aggregated-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:aggregated-metrics-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: front-proxy-client
