apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-adapter
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/stats
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
