apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    use: grafana-data
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /hostpath/grafana-data
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
