apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
spec:
  type: NodePort
  selector: {}
  ports:
    - port: 3000
      nodePort: 30030
      targetPort: grafui
