apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {}
  template:
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              protocol: TCP
              name: promui
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: data-volume
              mountPath: /prometheus
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: config-volume
          configMap:
            name: prometheus
        - name: data-volume
          persistentVolumeClaim:
            claimName: prometheus-data
