apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    use: prometheus-data
  name: prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /hostpath/prometheus-data
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
