apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-service-account
subjects:
  - kind: ServiceAccount
    name: node-exporter
    namespace: ""
